#!/usr/bin/env bash

# Install Nginx
sudo apt -y update
sudo apt -y upgrade
sudo apt -y install nginx

# Create the default webpage
echo 'Hello World!' |sudo tee /var/www/html/index.html

# Configure redirection
redirect="\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}"
sudo sed -i "/^\tlocation \// i\ $redirect" /etc/nginx/sites-available/default

# Create a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/index.html
sudo sed -i "/\t#error_page/s/#//g" /etc/nginx/sites-available/default
sudo sed -i "/^server {/a\ \tadd_header X-Served-By $(hostname);" /etc/nginx/sites-enabled/default

sudo service nginx restart

