#!/usr/bin/env bash

# Install Nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create the site root directory
sudo mkdir -p /var/www/html

# Create the default webpage
sudo touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html

# Create a custom 404 page
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

# Confiure Nginx to redirect, have a custom 404 page and a  custom HTTP header
printf %s "server {
    listen 80 default_server;
    listen [::]:80 default_server;
    add_header X-Served-By $HOSTNAME;
    root   /var/www/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4/;
    }
    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

# Restart Nginx after configurations
sudo service nginx restart
