#!/usr/bin/env bash
# Install and configure HAproxy on lb-01 server
sudo apt-get install --no-install-recommends software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.7
sudo apt-get update
sudo apt-get install haproxy=2.7.\*

# Backup default HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_real.cfg

# Configure HAproxy to send traffic to web-01 and web-02, distribute requests using a roundrobin algorithm and to be managed via an init script
echo -e "frontend alx-frontend\n\tbind\t*:80\n\tmode\thttp\n\tdefault_backend\talx-backend\n" >> /etc/haproxy/haproxy.cfg
echo -e "backend\talx-backend\n\tbalance\troundrobin\n\tserver\140268-web-01\t54.237.45.220:80\tcheck\n\tserver\140268-web-02\t54.237.63.152:80\tcheck\n" >> /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
