#!/usr/bin/env bash
# This script installs and sets up a load balancer
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo chown -R "$USER:$USER" /etc/haproxy/

# Backup default HAProxy configuration file
sudo cp -a /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_real.cfg

# Configure HAproxy to send traffic to web-01 and web-02, distribute requests using a roundrobin algorithm and to be managed via an init script
printf %s "
frontend alx-frontend
    bind *:80
    default_backend alx-backend
backend alx-backend
    balance roundrobin
    server 140268-web-01 54.237.45.220
    server 140268-web-02 54.237.63.152
" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
